use shellwego_schema::{BusConfig, BusMessage, ChannelPriority, Message, QuicConfig, SubscriptionId, Topic};
use anyhow::{Context, Result};
use std::net::SocketAddr;
use std::sync::Arc;

#[derive(Clone)]
pub struct QuinnClient {
    connection: Option<quinn::Connection>,
    config: QuicConfig,
    endpoint: Option<quinn::Endpoint>,
}

impl QuinnClient {
    pub fn new(config: QuicConfig) -> Self {
        Self {
            connection: None,
            config,
            endpoint: None,
        }
    }

    /// Connect to a QUIC server endpoint.
    ///
    /// TLS root certificates are loaded from the system's native certificate
    /// store via `rustls-native-certs`, with the Mozilla Web PKI roots
    /// (`webpki-roots`) as a fallback when the native store is empty (common
    /// in containers).
    pub async fn connect(&mut self, endpoint_url: &str) -> Result<()> {
        let addr: SocketAddr = endpoint_url
            .parse()
            .context("Invalid endpoint URL")?;

        // Build a root certificate store with native certs + webpki fallback.
        let mut root_store = rustls::RootCertStore::empty();

        // Try loading native (OS) certificates first.
        let native_certs = rustls_native_certs::load_native_certs()
            .context("Failed to load native certificates")?;

        let (added, ignored) = root_store.add_parsable_certificates(native_certs);
        tracing::debug!(
            "Loaded {} native root certs ({} ignored)",
            added,
            ignored,
        );

        if added == 0 {
            // Native store was empty – common in minimal containers / CI.
            // Fall back to the bundled Mozilla Web PKI root certificates.
            root_store.extend(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());
            tracing::info!(
                "No native root certs found – using webpki-roots ({} certs)",
                webpki_roots::TLS_SERVER_ROOTS.len(),
            );
        }

        let mut tls_config = rustls::ClientConfig::builder()
            .with_root_certificates(root_store)
            .with_no_client_auth();

        tls_config.alpn_protocols = vec![self.config.alpn_protocol.clone()];

        let endpoint =
            quinn::Endpoint::client("[::]:0".parse().unwrap()).context("Create endpoint")?;

        let crypto = quinn::crypto::rustls::QuicClientConfig::try_from(tls_config)
            .context("Failed to create QUIC crypto config")?;
        let quinn_config = quinn::ClientConfig::new(Arc::new(crypto));

        // Use the hostname from the socket address as the TLS server name (SNI).
        let server_name = "shellwego";

        let connecting = endpoint
            .connect_with(quinn_config, addr, server_name)
            .context("Connect")?;
        let connection = connecting.await.context("Handshake")?;

        self.connection = Some(connection);
        self.endpoint = Some(endpoint);

        Ok(())
    }

    /// Connect to a QUIC server using a self-signed certificate.
    ///
    /// This is intended for development / testing where the server uses a
    /// self-signed cert generated by `rcgen`.  The provided DER-encoded
    /// certificate is added as a trust anchor.
    pub async fn connect_with_self_signed_cert(
        &mut self,
        endpoint_url: &str,
        cert_der: &[u8],
    ) -> Result<()> {
        let addr: SocketAddr = endpoint_url
            .parse()
            .context("Invalid endpoint URL")?;

        let mut root_store = rustls::RootCertStore::empty();
        root_store.add(
            rustls_pki_types::CertificateDer::from(cert_der.to_vec()),
        )?;

        let mut tls_config = rustls::ClientConfig::builder()
            .with_root_certificates(root_store)
            .with_no_client_auth();

        tls_config.alpn_protocols = vec![self.config.alpn_protocol.clone()];

        let endpoint =
            quinn::Endpoint::client("[::]:0".parse().unwrap()).context("Create endpoint")?;

        let crypto = quinn::crypto::rustls::QuicClientConfig::try_from(tls_config)
            .context("Failed to create QUIC crypto config")?;
        let quinn_config = quinn::ClientConfig::new(Arc::new(crypto));

        let server_name = "shellwego";

        let connecting = endpoint
            .connect_with(quinn_config, addr, server_name)
            .context("Connect")?;
        let connection = connecting.await.context("Handshake")?;

        self.connection = Some(connection);
        self.endpoint = Some(endpoint);

        Ok(())
    }

    /// Send a raw `Message` to the QUIC server.
    pub async fn send(&self, message: Message) -> Result<()> {
        let connection = self.connection.as_ref().context("Not connected")?;
        let data = postcard::to_allocvec(&message).context("Serialize")?;
        let (mut send_stream, _recv_stream) = connection.open_bi().await.context("Open stream")?;
        send_stream.write_all(&data).await.context("Write")?;
        send_stream.finish().context("Finish")?;
        Ok(())
    }

    /// Receive a raw `Message` from the QUIC server.
    pub async fn receive(&self) -> Result<Message> {
        let connection = self.connection.as_ref().context("Not connected")?;
        let (_send_stream, mut recv_stream) =
            connection.accept_bi().await.context("Accept stream")?;
        let data = recv_stream
            .read_to_end(10 * 1024 * 1024)
            .await
            .context("Read")?;
        postcard::from_bytes(&data).context("Deserialize")
    }

    // -----------------------------------------------------------------------
    // Bus-aware methods (Plan 03)
    // -----------------------------------------------------------------------

    /// Publish a message to a topic on the bus.
    ///
    /// Creates a `BusMessage` envelope and sends it as a `Message::Publish` variant.
    /// Returns the `msg_id` of the published message.
    pub async fn publish(
        &self,
        topic: &str,
        payload: Message,
        priority: ChannelPriority,
    ) -> Result<uuid::Uuid> {
        let connection = self.connection.as_ref().context("Not connected")?;

        let topic = Topic::new(topic).context("Invalid topic name")?;
        let bus_msg = BusMessage::new(topic, payload, priority);
        let msg_id = bus_msg.msg_id;

        let envelope = bus_msg.to_envelope().context("Failed to create envelope")?;
        let msg = Message::Publish {
            bus_message: envelope,
        };

        let data = postcard::to_allocvec(&msg).context("Serialize publish message")?;
        let (mut send_stream, _recv_stream) = connection.open_bi().await.context("Open stream")?;
        send_stream.write_all(&data).await.context("Write")?;
        send_stream.finish().context("Finish")?;

        Ok(msg_id)
    }

    /// Subscribe to a topic pattern.
    ///
    /// Sends a `Message::Subscribe` to the server. After subscribing,
    /// the server will forward matching messages to this connection.
    pub async fn subscribe(&self, subscription_id: SubscriptionId, topic_pattern: &str) -> Result<()> {
        let msg = Message::Subscribe {
            subscription_id,
            topic_pattern: topic_pattern.to_string(),
        };
        self.send(msg).await
    }

    /// Unsubscribe from a topic.
    ///
    /// Sends a `Message::Unsubscribe` to the server.
    pub async fn unsubscribe(&self, subscription_id: SubscriptionId) -> Result<()> {
        let msg = Message::Unsubscribe {
            subscription_id,
        };
        self.send(msg).await
    }

    /// Send an acknowledgment for a received message.
    pub async fn ack(&self, msg_id: uuid::Uuid) -> Result<()> {
        let msg = Message::Ack { msg_id };
        self.send(msg).await
    }

    /// Send a negative acknowledgment for a failed message.
    pub async fn nack(&self, msg_id: uuid::Uuid, reason: &str) -> Result<()> {
        let msg = Message::Nack {
            msg_id,
            reason: reason.to_string(),
        };
        self.send(msg).await
    }

    /// Send a Ping to the server and wait for a Pong response.
    ///
    /// Returns the round-trip time as a `Duration`.
    pub async fn ping(&self) -> Result<std::time::Duration> {
        let start = std::time::Instant::now();
        let msg = Message::Ping {
            timestamp: chrono::Utc::now(),
        };
        self.send(msg).await?;

        match self.receive().await? {
            Message::Pong { .. } => Ok(start.elapsed()),
            other => anyhow::bail!("Expected Pong, got: {:?}", std::mem::discriminant(&other)),
        }
    }

    pub fn is_connected(&self) -> bool {
        self.connection
            .as_ref()
            .map(|c| c.close_reason().is_none())
            .unwrap_or(false)
    }

    pub async fn close(&self) {
        if let Some(connection) = &self.connection {
            connection.close(0u8.into(), b"close");
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_client_new() {
        let config = QuicConfig::default();
        let client = QuinnClient::new(config);
        assert!(!client.is_connected());
    }

    #[test]
    fn test_client_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        assert!(!client.is_connected());
    }

    #[tokio::test]
    async fn test_client_close_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        // close() on a non-connected client should be a no-op
        client.close().await;
        assert!(!client.is_connected());
    }

    #[tokio::test]
    async fn test_send_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.send(Message::Heartbeat {
            node_id: uuid::Uuid::nil(),
            cpu_usage: 0.5,
            memory_usage: 0.3,
        }).await;
        // Should fail with "Not connected"
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_receive_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.receive().await;
        // Should fail with "Not connected"
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_publish_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.publish(
            "test.topic",
            Message::Ping { timestamp: chrono::Utc::now() },
            ChannelPriority::Command,
        ).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_subscribe_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.subscribe(SubscriptionId(1), "agent.*").await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_unsubscribe_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.unsubscribe(SubscriptionId(1)).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_ack_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.ack(uuid::Uuid::nil()).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_nack_when_not_connected() {
        let client = QuinnClient::new(QuicConfig::default());
        let result = client.nack(uuid::Uuid::nil(), "test reason").await;
        assert!(result.is_err());
    }
}
