apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shellwego.fullname" . }}
  labels:
    {{- include "shellwego.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "shellwego.databaseUrl" . | quote }}
  {{- if .Values.config.jwtSecret }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  {{- else }}
  JWT_SECRET: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if .Values.config.vaultToken }}
  VAULT_TOKEN: {{ .Values.config.vaultToken | quote }}
  {{- end }}
